cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/Users/gudbergur/Dropbox/Skoli/Hugbu\xcc\x81na\xc3\xb0arfr\xc3\xa6\xc3\xb0i/verkefni2/waf/.waf-1.6.1-99d4cb3b3c22e4e563a31e817c0d3d50/waflib/Tools/c_config.py", line 421, in run_c_code\n    bld.compile()\n  File "/Users/gudbergur/Dropbox/Skoli/Hugbu\xcc\x81na\xc3\xb0arfr\xc3\xa6\xc3\xb0i/verkefni2/waf/.waf-1.6.1-99d4cb3b3c22e4e563a31e817c0d3d50/waflib/Build.py", line 187, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task failed (exit status 1): \n\t{task 4316368144: cxx test.c -> test.c.0.o}\n[\'/usr/bin/g++\', \'-DHAVE_STDIO_H=1\', \'\', \'../test.c\', \'-c\', \'-o\', \'\', \'test.c.0.o\']\n'
